env:
  global:
    - secure: "alX+1SJrEr3X9ksv8Fmm+l6VCzQdQQt1qXnWh6uvDH9oaOa0GABhbu+iInJM9+PMaCwtt/rCvgn5NgRdEYpUpkFdXDXpWHGiaotUFh+Qm31J61Ly4+1K5tDELM3XAa2b67RfJKZc/LYjQuJ7hSU5axSdw+pIvl9PI+dUWCod73YHDZ89LzAelALk4sL0ClNF+zBQ26aEwZ+LNyItIjugO0Z2FYTVQh5BjhzDB3npICdwrN8zDK3CFFNO9s3KSfPx/+1S0uIHQQ4BpFH5166a4cWs06pmVWqR+AXetmBKe2KHCJhdgmLtfiIzhorimRFBAV1YOlocrDPhxThfvbBtYMpIvu+N/03extNrlzU/haMztDaq+UqXbYux00CCw2WdqXwDoDjYPf0gp0NpFLk4L0Sa7hSdpOn3cVTQ6zGYs4/Aufc+q6/JoMdCkLllfSIQsk1pP75lGbJ7E4AbIrfzji2bOIpneumL30Nhj3S3QjYqea53rYM7RsczsK3xxjmbKUal7Lb/sMWzZfwzLaouQGPqQBul4WWmwHDDVgu0FFiwCRQ5JQ0bdwhZ750QeemnhwoPx2yG3TzU2YCSFi4+RVbPLpiBdFIqm3ARu4xDPEY1h0mRd0Wb3/H0DKvL1m28SdkpHAtRBI4Mow31HTZhtJEX6gKhE7UJBOqGJ8q06FA="
language: node_js
node_js:
  - "8"
script:
  - npm test
after_success:
  - npm run-script build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  repo: opencrypto-io/data
  target_branch: gh-pages
  fqdn: data.opencrypto.io
