name: TRON
web:
  - 'https://tron.network/'
start_date: '2017-09-28'
ledgers:
  - id: tron
    name: Tron
    type: blockchain
    networks:
      - id: main
        type: main
        name: Mainnet
        proof_type: PoW+PoS
        mineable: true
        algorithm: Lamport algorithm
        target_block_time: 15
        tools:
          - type: explorer
            url: https://tronscan.org/#/
      - id: test
        type: test
        name: Testnet
        tools:
          - type: explorer
            url: https://test.TRONscan.org
assets:
  - id: trx
    type: native
    name: Tronix
    symbol: TRX
    ledger: tron
    start_date: '2018-04-16'
    ico_properties:
      start_date: '2017-08-31'
      end_date: '2017-09-02'
      raised: 70000000 USD
  - id: trx
    type: token
    name: Tronix
    symbol: TRX
    ledger: ethereum
    contract_address: '0xf230b790e05390fc8295f4d3f60332c93bed42e2'
    decimals: 6
    webids:
      coinmarketcap: TRON
      cryptocompare: trx
    denominations:
      subunits:
        - unit: 0.000001
          name: sun
    max_supply: 100000000000
clients:
  - id: tronscan
    name: Tronscan
whitepapers:
  - title: Tron
    url: https://o836fhe91.qnssl.com/tron/whitebook/TronWhitepaper_en.pdf
team:
  - name: Justin Sun
    role: Founder, CEO
    webids:
      linkedin: sunyuchen
      twitter: justinsuntron
  - name: Taihao Fu
    role: Software engineer
    webids:
      linkedin: taihao-fu-b6919459
history:
  - date: '2018-05-31'
    title: Tron begins transition to its own blockchain
    url: https://www.ccn.com/tron-begins-transition-to-its-own-blockchain/
webids:
  github: tronprotocol
  bitcoinwiki: TRON
  reddit: Tronix
  twitter: Tronfoundation
  facebook: TronFoundation-144555002795817
  youtube/channel: UC5OPOGRq02iK-0T9sKse_kA?view_as=subscriber
  linkedin/company: tronfoundation
  telegram: kleros tronnetworkEN03
  medium: kleros Tronfoundation
  custom/chat: https://tronfoundation.slack.com/
